ubports/installer-configs

v1/oneplus3.json

This adds install config for oneplus3, this does not include checksums for partition images
This is still experimental, so should not be added to index just yet.

Add oneplus3 install config

---

v1/arale.json
v1/cooler.json
v1/deb.json
v1/flo.json
v1/frieza.json
v1/hammerhead.json
v1/krillin.json
v1/suzu.json
v1/turbo.json
v1/vegetahd.json

Since the UBports Installer supports these starting with the next version, it's time to get these in there. Does not break compatibility with older versions of the installer.

Add unlock steps for legacy android devices

---

aliases.json
index.json
v1/suzu.json

Due to recent changes in the Halium portion of the suzu port we now
support the F5122 variant of the Xperia X with the same image.

suzu: Add support for the F5122 (Dual SIM) variant

---

v1/suzu.json

The new recovery contains the fix for the SD card
locking up the recovery initialization at startup.

suzu: Update recovery checksum

---

aliases.json
index.json
v1/dora.json

This is derived from Sony Xperia X
recovery image is from a locked dora build.
It also needs the flashing of the recovery image to boot, because it does not like to boot recovery directly via fastboost.

Adds Sony X Performance

---

.travis.yml

Since we only use this to validate json, there is no need to do it on more then one type of machine.

Remove osx and node versions

---

v1/hammerhead.json

Should prevent further bug-reports like
https://github.com/ubports/ubports-installer/issues/1107
Please note that I didn't run the commands suggested in the README.md, due to not having npm & co installed. I ran the installer with my modified config files via the `-f` flag though and the message was displayed like expected.

Hammerhead: Add partition layout warning

---

v1/suzu.json

Updates suzu.json config to make use of new manual_download functionality and flash in a working order. Fixes #37

Flash manually downloaded OEM binaries on Suzu

---

v1/santoni.json

The old build was cleaned from Jenkins since it was not specified to keep forever. I've set that setting on this pair of images.

Update boot and recovery for santoni

---

index.json
v1/sargo.json

This PR includes new device support for the Google Pixel 3a.
Full device support is dependent on changes in the rootfs, so keep this PR as a draft until those issues have been solved.

Add Pixel 3a (sargo)

---

aliases.json

As reported in the supergroup, the oneplus 3 t may introduce itself as msm8996 if detected via fastboot getvar. it was to be expected that we would have to add new aliases, but this is a little annoying, because msm8996 is not a device id, but the name of the chipset. if we have multiple devices with the same chipset and they all don't set this var properly, we'll have trouble and suffering. Let's add this anyways for now, if we do get duplicates, we'll implement a UI to prompt the user to select the right device. For now, this can be merged.

Add msm8996 alias for oneplus3

---

index.json
v1/pro1.json

This is a port of Ubuntu Touch to the Fxtec Pro1. It installs and boot perfectly fine.
CC: @NotKit @NeoTheThird 
EDIT: Is it possible for us to have the boot.img on cdimages? That'd be nice as GitLab tends to delete artifacts.

Add Fxtec Pro1 configuration

---

v1/sargo.json
v2/devices/sargo.yml

Turns out that some devices have their primary boot slot
set to 'a' after a factory image installation, so revert
the use of slot selection altogether.

sargo: Remove slot selection

---

v1/angler.json
v1/dora.json
v1/kagura.json
v1/kugo.json
v1/oneplus2.json
v1/santoni.json
v1/trlte.json
v1/trltespr.json
v1/trltetmo.json
v2/devices/angler.yml
v2/devices/dora.yml
v2/devices/kagura.yml
v2/devices/kugo.yml
v2/devices/oneplus2.yml
v2/devices/santoni.yml
v2/devices/trlte.yml
v2/devices/trltespr.yml
v2/devices/trltetmo.yml

All of the jobs that were linked to are no longer enabled. Rather than moving to new builds on the CI server which could change over time, use the static cdimage server instead.
This requires testing:

Move remaining devices to static hosting

---

v1/yggdrasil.json
v2/devices/yggdrasil.yml

Flashing the `boot.img` inside the Android flashable zip is not needed as this is already done by the updater-script while it is flashed in recovery mode on the device.
Fixes https://github.com/ubports/ubports-installer/issues/1620.
Fixes https://github.com/ubports/ubports-installer/issues/1712.

yggdrasil: Fix Volla OS flashing issue

---

v2/schema/action.schema.yml

New actions requested in https://github.com/ubports/ubports-installer/issues/1828 and implemented in https://github.com/ubports/ubports-installer/pull/1827.
Example:
```
- actions:
- core:info:
status: "doing something"
dots: true
progress: 0.1
info: "running command whatever"
- adb:shell:
args: ["echo", "hi"]
```
cc @JamiKettunen

Document adb:shell and core:info actions

---

v2/devices/violet.yml

The installer is able to unpack files, so let's do it for us.
Also, add a few more partitions which might be different depending on
the Android version.

violet: avoid manual unpacking step

---

v2/devices/yggdrasil.yml

Once AOSP 10-based update to Volla OS is released, it will change bootloader, vendor and other system partitions we depend on. Since A10 bootloader is not compatible with A9 image format, we need to flash *all* the system partitions to install Ubuntu Touch on such devices.
The change makes Installer download the relevant firmware archive from volla.tech and flash partitions via fastboot if bootstrap is requested, which should work with both existing A9 and updated to A10 devices.

yggdrasil: flash all the system partitions in bootstrap action

---

v2/devices/beryllium.yml

I m using `ubports-installer-support.zip` to hold the firmware, vendor and ubports recovery image. This makes manual download a bit easier for the user, as they are not needed to enter the path for each file. 
For reference:
1. Firmware - V11.0.5.0.PEJMIXM (Android 9 based firmware is needed for Poco F1, but most of the devices are updated to android 10 which doesnt work)
2. vendor.img - Lineage 16.0 vendor partition
3. recovery.img - Ubports Recovery

beryllium: Add Xiaomi Poco F1

---

aliases.json
v1/sargo.json
v2/devices/sargo.yml

Add an alias from 'bonito' to 'sargo' as both the non-XL & XL variants
can use the same system, kernel and dtbo images.
Also adapt the hints to reference the XL variant.

configs: Initial support for Google Pixel 3a XL

---

v2/devices/perseus.yml

Adding installer configs for Xiaomi Mi MIX 3 (perseus), tested and confirm successful installation via `ubports-installer --file perseus.yml`.
Since most of users are on Android 10, Android 9 vendor is needed to boot. I included stock Android 9 vendor as part of the installer (source: [V9.9.3](https://xiaomifirmwareupdater.com/miui/perseus/weekly/9.9.3/)).
The dtbo.img is also required to boot, the one from stock doesn’t work. It was built locally from halium 9 porting.

perseus: add Xiaomi Mi MIX 3

---

v2/devices/miatoll.yml

Tested multiple times, breaks only if the installer already succeeded thus I avoided flashing  `recovery.img` to the boot partition so it won't break the booting process.

miatoll: add Xiaomi Redmi Note 9 Pro/Pro Max/9S - Poco M2 Pro

---

v2/devices/begonia.yml

Currently adb push is not working in reliable way with the device. This change avoids using it at the cost of flashing prebuild OTA 19 image, which then can be updated from system settings.

begonia: hack: flash boot.img and system.img with fastboot

---

v2/devices/violet.yml

Flashing this partition allows installing Ubuntu Touch directly from a
preexisting Android or MIUI installation. Without it, it's only possible
to install Ubuntu Touch from a preexisting LineageOS installation.

violet: add vbmeta partition

---

v2/devices/yggdrasil.yml

Hi There,
I just tried to flash Volla OS to a Volla Phone but I got an error during unpacking.
This seems to be related to the archive name, which is different from the downloaded file name.
After updating the archive name in the yml file, the procedure worked as expacted.
The archive name is fixed with this pull request.
best regards,
Daniel

Unpacking Volla OS zip fails due to wrong archive name.

---

v2/devices/violet.yml

I recently uploaded a new vendor image at the same URL, and forgot to update the checksum! Ooops!

devices: update checksum for violet vendor image

---

v2/devices/FP3.yml

Fixes Error: {"error":{"code":1,"cmd":"adb -P 5037 shell mkdir -p /cache/recovery"},"stderr":"mkdir: '/cache/recovery': Required key not available"}
^^ Appears on first installs, coming from Android OS'.

FP3: Fix pushing data to phone, when userdata is encrypted

---

v2/devices/taimen.yml
v2/devices/walleye.yml

Due to https://github.com/ubports/ubuntu-touch/issues/1916 we had to update boot images

Pixel 2: Update boot.img checksums

---

v2/devices/miatoll.yml

The kernel has been changed, and upstreamed.
The dtbo image isn't flashed by the device OTAs and some fixes depends on the new one.

miatoll: add new recovery and dtbo images

---

v2/schema/action.schema.yml

This allows devices to format partitions as `f2fs`.

schema: add "f2fs" to partition type enum

---

v2/schema/action.schema.yml

Devices, which are launching with Android 10 and higher, are required to implement [Dynamic Partitions](https://source.android.com/devices/tech/ota/dynamic_partitions/implement).
This requires a different workflow when installing, such as resizing super partitions or rebooting to userspace fastboot ([fastbootd](https://source.android.com/devices/bootloader/fastbootd)) mode to flash logical partitions located withing the physical super partition.
```
- fastboot:reboot_fastboot:
```
```
- fastboot:reboot_recovery:
```
```
- fastboot:wipe_super:
image:
file: "super_empty.img"
group: "firmware"
```

Implement additional fastboot actions

---

v2/devices/jingpad_a1.yml

The missing button causes flash attempts with "Wipe" enabled to
stay stuck at the instruction without a button to continue.
Also instruct the user to reboot the device after wiping.

v2/devices: Refine Factory Reset portion for JingPad A1

---

v2/devices/laurel_sprout.yml

At last, I have implemented the Xiaomi Mi A3 (laurel_sprout) to the UBports installer. A few notes should be considered:
Two workarounds have been added regarding some issues with dtbo. The first one is an option to reflash dtbo on the "OS" section of the installer. The second is during regular installation, after flashing the system image, in which the user is prompted to reboot their device into the bootloader and flash dtbo, after which the user is prompted again to reboot into recovery to finish the installation. If users don't have any issues during a regular install, it's possible to remove the first one.
The images are currently being pulled from the UBports laurel_sprout CI and from the original kernel tree's CI (https://gitlab.com/nixeko/halium-ports/laurel_sprout/lunecrash/). We …

devices: Added support for Xiaomi Mi A3 (laurel_sprout)

---

v2/devices/miatoll.yml

Fixes all the miatoll issues related to https://github.com/ubports/ubports-installer/issues/2147

Fix updating Ubuntu Touch using the Ubports Installer.

---

v2/devices/axolotl.yml

This adds the config file for SHIFT6mq (axolotl) and also adds `f2fs` as supported partition type (which is used by axolotl).

devices: add support for SHIFT SHIFT6mq (axolotl)

---

v2/devices/lavender.yml

This allows the user to download the zip file and drop it in the installer and installer will take over from there.
Fixes https://github.com/ubports/ubports-installer/issues/2506 fixes https://github.com/ubports/ubports-installer/issues/2066 fixes https://github.com/ubports/ubports-installer/issues/1871

lavender: unpack the zip file instead of the user

---

v2/devices/FP3.yml
v2/devices/X605.yml
v2/devices/axolotl.yml

Looks like we'll have to communicate the existing features like `code_url` better. Hacks like these should not be in the configs! They are poorly accessible, redundant, and only create confusion. Worst case, they go out of date.

Remove redundant bootloader unlock instructions

---

v2/devices/axolotl.yml

This allows restoring stock and allows choosing between G and L Version of stock.
- G - normal retail version with Google Apps
- L - aftermarket version, which is equal to G, but has all Google Apps and Services removed

v2: devices: axolotl: add support for ShiftOS G / L restoration

---

v2/devices/yggdrasilx.yml

Current stable OTA channel is based on A10 BSP, so installer needs to use A10 firmware too

yggdrasilx: use Android 10 BSP firmware for Ubuntu Touch installation

---

v2/devices/lancelot.yml

The config for lancelot didn't contain the alias for the european variant of Redmi 9. The only thing separating them is that the european variant does have a NFC module and a different codename.

lancelot: Add support for european variant "galahad"

---

v2/devices/surya.yml

This adds a repartitioned super.img to make space in the rootfs. This fixes installing Waydroid.
vendor.img also contains additional libraries to enable FM radio support.
Command used to generate `super.img`:
```
lpmake --metadata-size 65536 --metadata-slots 2 \
--super-name super --device super:8589934592 \
--group qti_dynamic_partitions:8581545984 \
--partition system:none:5368709120:qti_dynamic_partitions \
--partition vendor:none:2147483648:qti_dynamic_partitions \
--output super.img
```
8589934592 bytes = 8GB (size of the super partition)
8581545984 bytes = 8GB - 8kB
5368709120 = 5GB (size of the system partition)
2147483648 = 2GB (size of the vendor partition)
`
recovery.img` and `dtbo.img` stay unchanged.

surya: repartition rootfs with custom super.img

---

v2/devices/X605.yml

Kernel got some updates and therefor a new boot-image is needed.

Lenovo-X605: adjusted aliases, updated bootimage

---

v2/schema/action.schema.yml

This implements the following new action:
```
- actions:
- fastboot:create_logical_partition:
partition: "partition_name"
size: 3221225472
- fastboot:delete_logical_partition:
partition: "partition_name"
- fastboot:resize_logical_partition:
partition: "partition_name"
size: 3221225472
```
These actions are required for certain devices with
dynamic partitions, like the Fairphone 4.

v2: schema: add commands for interacting with logical partitions

---

v2/devices/FP3.yml

New boot-image includes some kernel changes regarding performance and bluetooth.
Additionally in halium-script-overlay in ramdisk, the widi option now gets activated.

Fairphone FP3: updated boot.img and hashcode

---

v2/devices/hero2lte.yml
v2/devices/herolte.yml

How long do artifacts lasts? I see the fp3 yml using that for shipping the recovery image.
How to make systemimage available to the installer?
Last CI run:
https://gitlab.com/ubports/porting/community-ports/android11/samsung-galaxy-s7/samsung-exynos8890/-/pipelines/597880645

adding galaxy s7 exynos (flat and edge)

---

v2/devices/yggdrasil.yml

This caused Volla Phone X (`yggdrasilx`) to be detected as Volla Phone (`yggdrasil`) while in bootloader mode (`fastboot`) and continuing with the flashing would soft-brick the device until reflashed with the correct firmware using low level SP flash tool.
Potentially fixes https://github.com/ubports/ubports-installer/issues/2833.

volla-yggdrasil: Remove alias

---

v2/devices/mimameid.yml

The [Volla Phone 22](https://volla.online/de/shop/volla-phone-22/) has had an option to ship with Ubuntu Touch out of the box but hasn't yet had a [UBports installer](https://devices.ubuntu-touch.io/installer/) config.
A [devices.ubuntu-touch.io](https://devices.ubuntu-touch.io/) page is also almost done, I'll check differences between devel, stable and UT as a 2nd OS (dual-boot).

devices: Add initial config for Volla Phone 22 (mimameid)

---

v2/devices/dandelion.yml

* Boots reliably on Redmi 9A now, with working fastbootd

devices: dandelion: Add new recovery.img for bootstrap

---

v2/devices/pro1.yml
v2/devices/pro1x.yml

This adds installer config for the newer Fxtec Pro1 X and removes erroneous mention of Pro1 X from the original Pro1 config. 
Please upload https://gitlab.com/ubports/porting/community-ports/android11/fxtec-pro1x/fxtec-pro1x/-/jobs/4181610683/artifacts/raw/out/recovery.img to https://cdimage.ubports.com/devices/pro1x/recovery.img

devices: Add installer config for Fxtec Pro1 X (pro1x)

---

v2/devices/sargo.yml
v2/devices/yggdrasil.yml

This pull request contains the following updates:
- Updated Droidian download URL on sargo. Pixel 3a has re-gained status as an official port and the official download URL should be used.
- Updated the broke Droidian install directives for yggdrasil. The configuration to install Droidian on Volla Phone has been broken for a while. This fixes it and switches to fastboot installable images which are the preferred way to install as of now.
- Also, add Cutie variant for both sargo and yggdrasil. This downloads from CutieShell CI and also has an appropriate notice displayed to user about the status of Cutie.

sargo/yggdrasil: Droidian related fixes/additions

---

v2/devices/mimameid.yml

mimameid has now official support on Droidian and is built on the official Droidian CI. Also, Droidian/Cutie is working and built by Cutie CI.
This PR adds the possibility to install these Droidian images either with phosh or Cutie on Volla Phone 22.

mimameid: Add Droidian support

---

v2/devices/angelica.yml
v2/devices/lavender.yml
v2/devices/onclite.yml

On these devices, the Droidian download URLs should be updated as the devices have been moved to official status. Also, similarly to other devices, adding Cutie as an option alongside phosh should be done.

angelica/lavender/onclite: Use official Droidian download and add Cutie option

---

v2/devices/vidofnir.yml

Otherwise there will be problems during install since `f2fs` isn't specified in recovery `fstab` etc.
Fixes https://github.com/ubports/installer-configs/pull/240#issuecomment-1668697513.

vidofnir: Ensure UT userdata is formatted as ext4

---

v2/devices/miatoll.yml

The recovery and dtbo images were updated so this commit is to update their SHA checksum

Update miatoll.yml recovery and dtbo SHA

---

package-lock.json
tsconfig.json
v2/build.ts
v2/checkDownloads.ts
v2/checkSemver.ts
v2/cli.ts
v2/schemas.ts

Trying to fix the CI build without any knowledge of node and typescript...

WIP: CI: fix ts-node/esm build

---

v2/devices/mimameid.yml

- If the current slot is 'b' (as it can be if Android has been updated), even if we set the (new) active slot to 'a', we still have to explicitly spell out the slot.
- vbmeta has to be flashed, replacing the one from Android. The new bootstrap tarball is provided by Volla to include vbmeta.

volla-mimameid: fix coming (back) from Android

---

v2/devices/mimameid.yml

Due to a serious problem with a lvm installation of Droidiain on mimameid, Droidian's mimameid builds were reverted to use a recovery-sideloadable zip with rootfs.img.
This pull request adapts the installer configuration to use this package type.

mimameid: Fix Droidian support

---

v2/devices/X605.yml

* added hint for 2GB/16GB models
* fixed links to to gitlab community-ports
* updated boot.img and checksum
* removed after_install hint, which is not necessary anymore

Lenovo X605: 20.04: updated config for compatibility with focal builds

---

v2/devices/FP4.yml

~~TODO: Needs testing~~ Tested, works as expected.

FP4: minor updates

---

v2/devices/surya.yml

Currently, Xiaomi POCO X3 (karna) and Xiaomi POCO X3 NFC (surya) use the same images (system and kernel) and the same [device page](https://devices.ubuntu-touch.io/device/surya/).
But only surya is installable with the UBports installer.
As suggested at https://t.me/ut_pocox3/13719, this MR add support for the indian variant (karna).

surya: Add support for indian variant

---

v2/devices/X00TD.yml

Link doesn't give bootloader unlocking information anymore. This MR uses the previous version from archive.org

Fix link in X00TD.yml

---

v2/devices/billie.yml

This update boot with the last fix to the bluetooth stack that cused device to freeze and reboot into panic mode.

Update boot.img with fixed bluetooth stack

---

v2/devices/vidofnir_esim.yml

Matching what is currently available devel pending at least firmware tarball promotion to both RC and stable before this is merged to avoid soft-bricking new installations.

vidofnir_esim: Update Ubuntu Touch firmware bootstrap archive
