v1/suzu.json

This adds support for the Sony Xperia X (aka suzu).

suzu: Add config for the Xperia X

---

index.json
v1/suzu.json

- Append "F5121" device identification to device names
- Implement userdata wipe
- Update description to enter fastboot mode

suzu: Multiple changes

---

v1/_device.schema.json

Some more validation and documentation i started a while back. For #1, we still need a little more, but it does not make sense for me to just have it lying around in git stash. Might as well commit it.

Add more validation/documentation

---

v1/hammerhead.json

Should fix https://github.com/ubports/ubports-installer/issues/1045. Not sure if it works.

option to format data and system

---

aliases.json

As seen here: https://github.com/faust93/android_device_meizu_m86

Add pro 5 alias m86

---

v1/suzu.json

see https://forums.ubports.com/topic/3229/sony-xperia-x-suzu-f5121

Upgrade android on suzu

---

README.md

Hi,
I noticed this typo and thought to grab it quickly.
Let me know if the commit message needs any help.

Fix typo - s/index.js/index.json/g

---

aliases.json
index.json
v1/kugo.json

This is pretty much identical to dora/suzu.

Add config for kugo

---

index.json

Guf installer configs

---

index.json
v1/santoni.json

This PR brings Redmi 4X into the device list.
So far, no issue and everything seems to work fine (and it even installs), however need someone to help with testing userdata format as I'm currently using this device as a daily driver and cannot risk wiping my data so until that's tested, this is a draft.

Add Redmi 4X (santoni)

---

v1/_device.schema.json
v1/yggdrasil.json

All things needed for the other VollaPhone OSs

VollaOS and SailfishOS for VollaPhone

---

index.json
v1/oneplus3.json

I think it is more understandable

change 3(T) to 3/3T

---

v1/yggdrasil.json

various fixes for the vollaphone

Vollaphone Fixes

---

aliases.json
index.json
v1/oneplus2.json

Add UT and LineageOS support for the OnePlus 2

Add oneplus2

---

v1/suzu.json

Fixes ubports/ubports-installer#1542

Let installer unpack manually downloaded suzu firmware

---

index.json
v1/jasmine_sprout.json

Added config for jasmine_sprout :)

jasmine_sprout (Xiaomi Mi A2) config added

---

aliases.json

same as a48886a0fb4f0d72c7962b5a4f8c5983333497dd #47

Add msm8994 alias for oneplus2

---

index.json
v1/s3ve3g.json
v2/s3ve3g.yml

Add Samsung S3 Neo (s3ve3g)

---

v2/devices/lenok.yml
v2/schema/action.schema.yml

To be merged when UBports Installer version 0.8.4-beta is live.

AsteroidOS plugin

---

v1/dora.json
v1/kagura.json
v2/devices/dora.yml
v2/devices/kagura.yml

Mostly taken from suzu configs.
@konradybcio as promised

v1/v2: dora,kagura: Add oem steps, cleanup

---

v2/devices/oneplus3.yml

* add instruction to avoid failed installation if Android 9 was installed
* fix wipe option
* add OxygenOS 9.0.6 support

Improve OnePlus3/3T options

---

v2/devices/oneplus3.yml

Or in other word
oops I forgot this case ^^'

Oneplus3: add fallback for Android 9 special case

---

v2/schema/action.schema.yml

Sister-PR to https://github.com/ubports/ubports-installer/pull/1818

Document new steps for systemimage plugin refactoring

---

v2/schema/action.schema.yml

Required for https://github.com/ubports/ubports-installer/issues/1611

Allow renaming downloaded files

---

v2/devices/yggdrasil.yml

Thanks to @NeoTheThird for implementing the `adb:shell` action!
I'm assuming all future changes should only apply to `v2` so I didn't touch the `v1` file.

Volla Phone (yggdrasil) fixes

---

v2/devices/violet.yml

violet: add XiaoMi Note 7 Pro

---

v2/devices/land.yml

land : add redmi 3s / 3x / 3sp

---

v2/devices/h815.yml

Config adapted for LG G4 (h815)

Add device LG G4 International (h815)

---

v2/devices/enchilada.yml

Hello! This is universal config for OnePlus 6/6T. Ubuntu Touch successfully installed on OnePlus 6/6T with this config.

enchilada: Add OnePlus 6/6T installer config

---

v2/devices/yggdrasil.yml

This downloads and installs Droidian (latest version).

yggdrasil: Add Droidian as an alternative OS

---

v2/devices/FP3.yml

(second try, previously I messed up my commits somehow)
As draft, because I want to wait for some feedback of testers, see:
https://forums.ubports.com/topic/6544/call-for-testing-fp3-config-for-ubports-installer/3

added installer config for Fairphone 3

---

v2/buildConfigs.js
v2/buildSchema.js

this would have prevented yesterday's problem from #126

Make aliases optional

---

v2/devices/sagit.yml

Build last lineage source(26.09.2021), enable vndk current

sagit: update vendor.img

---

v2/devices/lavender.yml

This pull request add a splash screen to the Redmi Note 7.

lavender: add splash logo

---

v2/devices/yggdrasilx.yml

New hardware revision needs this update.

volla-yggdrasilx: Update VollaOS

---

v2/devices/jingpad_a1.yml

Initial bringup of the JingPad config.

v2/devices: Add JingPad A1 configuration

---

v2/devices/jingpad_a1.yml

- Put cdimage URLs for firmware files
- Ship vendor image
- Fix forum link
- Do formatting of userdata manually due to fastboot issues

v2/devices: Modify JingPad config

---

v2/devices/X605.yml

New installer config for Lenovo Smart Tab M10 X605L/F.

Lenovo x605 - initial installer config

---

v2/devices/suzu.yml

suzu: use "https" for cdimage url

---

v2/devices/axolotl.yml

Never default to wipe user data

---

.github/workflows/ci.yml
package.json
v2/devices/angler.yml
v2/schema/action.schema.yml
v2/schema/checksum.schema.yml
v2/schema/device.schema.yml
v2/schema/expression.schema.yml
v2/schema/formfactor.schema.yml
v2/schema/operating_systems.schema.yml
v2/schema/options.schema.yml
v2/schema/regex.schema.yml
v2/schema/step.schema.yml
v2/schema/user_actions.schema.yml
v2/test/invalid/unused_user_action.yml
v2/test/valid/some_valid_config.yml

Some things to help improve clarity of the action specification. Even found an action that was completely broken, which i fixed in https://github.com/ubports/ubports-installer/pull/2542. This should help us improve config quality. More work needed, but it's something!

Action clarity

---

v2/devices/sargo.yml

Fixes: https://github.com/ubports/ubports-installer/issues/2734

v2: devices: sargo: add "bonito" as alias

---

v2/devices/merlin.yml

im tired of having to choose merlin manually

Add merlinnfc as alias for merlin

---

v2/devices/FP4.yml
v2/schema/action.schema.yml

devices: Config for the Fairphone 4

---

v2/schema/action.schema.yml

Add two new reboot targets:
- download (Samsung)
- edl (Qualcomm - QFIL)

v2: schema: action: add additional reboot targets

---

v2/devices/axolotl.yml
v2/devices/enchilada.yml
v2/schema/action.schema.yml
v2/schema/options.schema.yml

Add schema for postmarketOS support and add postmarketOS support to the following devices:
- axolotl
- enchilada

v2: add support for postmarketOS

---

v2/devices/cheeseburger.yml
v2/devices/dumpling.yml

Tested on a fresh 5t after unlocking the bootloader.

v2: devices: cheeseburger, dumpling: remove useless twrp step, clean up

---

v2/devices/enchilada.yml

v2: devices: enchilada: add links to postmarketOS release & interface

---

v2/devices/denniz.yml

https://gitlab.com/ubports/infrastructure/devices.ubuntu-touch.io/-/merge_requests/387

devices: Add initial config for OnePlus Nord 2 5G (denniz)

---

v2/devices/angelica.yml
v2/devices/dandelion.yml

* Installer support is finally fixed

devices: dandelion: Update sha256sum for dandelion recovery image

---

v2/devices/miatoll.yml

miatoll: Add Droidian support

---

v2/devices/FP5.yml

Add the ability to install postmarketOS on the device using the installer.
~~TODO: Test~~ Tested with gnome mobile install (postmarketOS edge)

devices: Add config for Fairphone 5

---

v2/devices/amar_row_wifi.yml
v2/devices/billie.yml
v2/devices/billie2.yml

- Add Lenovo Tab M10 HD 2nd Gen Wifi (amar_row_wifi)
- Add OnePlus Nord N10 (billie)
- Add OnePlus Nord N100 (billie2)

Add new devices to UBports Installer

---

v2/devices/billie.yml
v2/devices/billie2.yml

- fix sensor on OnePlus Nord N10 by flashing persist

Fix firmware links

---

v2/devices/miatoll.yml

the links on the github page linked for miatoll are broken, updated to the current working link

replace broken link miatoll

---

v2/devices/algiz.yml

As usual works but could use more testers, @ruditimmermans will try later and possibly can report back here how it works switching from VollaOS

devices: Add initial config for Volla Phone Quintus (algiz)

---

v2/devices/amar_row_lte.yml

- Replace recovery that causes bootloop on device

Fix recovery amar_row_lte

---

v2/devices/r1.yml

* All images are built from UB touch CI on ubports gitlab.
* Device sources are already present on gitlab.

installer-configs: Welcome rabbit r1
